Anticom\KennzeichenBundle\Entity\Bundesland:
  properties:
    name:
      - NotNull:
        message: "Der Name darf nicht leer sein"
      - NotBlank:
        message: "Der Name darf nicht leer sein"
      - Length:
        min: 5
        minMessage: "Der Name muss mindestens 3 Zeichen lang sein"

Anticom\KennzeichenBundle\Entity\Kennzeichen:
  properties:
    kuerzel:
      - NotNull:
        message: "Das K端rzel darf nicht leer sein"
      - NotBlank:
        message: "Das K端rzel darf nicht leer sein"
      - Length:
        min: 1
        max: 3
        minMessage: "Das K端rzel muss mindestens 1 Zeichen lang sein"
        maxMessage: "Das K端rzel darf maximal 3 Zeichen lang sein"
    kreis:
      - NotNull:
        message: "Der Kreis darf nicht leer sein"
      - NotBlank:
        message: "Der Kreis darf nicht leer sein"
      - Length:
        min: 3
        minMessage: "Der Kreis muss mindestens 3 Zeichen lang sein"
    bundesland:
      - NotNull:
        message: "Das Bundesland darf nicht leer sein"
      - NotBlank:
        message: "Das Bundesland darf nicht leer sein"