Anticom\KennzeichenBundle\Entity\Bundesland:
  exclusion_policy: NONE
  xml_root_name: Bundesland
  properties:
    id:
      xml_attribute: true
    kennzeichen:
      type: array<Anticom\KennzeichenBundle\Entity\Kennzeichen>
      xml_list:
        inline: true
        entry_name: kennzeichen